### ISSUE TITLE
Not able to add it to XCODE gives error

### ISSUE THREAD

**Issue by sp062** [nextgis/ios_maplib#2]
xcode gives error saying not able find ngstore  .

**Comment by BishopGIS** [comment]
Please describe your steps to reproduce. 
1. You Mac OS version? XCode version?
2. Do you create Cartfile and execute `carthage update --platform "iOS"`? Do you follow this steps https://github.com/Carthage/Carthage/#if-youre-building-for-ios-tvos-or-watchos ?
3. Does the command executed successfully? On my Mac it usually build about 30-40 minutes from scratch.
4. Do the Carthage/Build/iOS folders exists? Do ngmaplib.framework and ngstore.framework frameworks exists?
5. Do you disable bitcode in your project?
6. What is error message?

Also you may check demo application settings in this repository: https://github.com/nextgis/ios.mobile.demo

**Comment by BishopGIS** [comment]
No feedback
